names = ['john', 'NINA', 'sara', 'brad']
print(len(names))
print('Dear ' + names[0].title() + ', you are invited to dinner' + '.')
print('Dear ' + names[1].title() + ', you are invited to dinner' + '.')
print('Dear ' + names[2].title() + ', you are invited to dinner' + '.')
print('Dear ' + names[3].title() + ', you are invited to dinner' + '.')
lost_guest = 'NINA'
names.remove(lost_guest)
names.insert(1,'Anna')
print('List changed')
print('Dear ' + names[0].title() + ', you are invited to dinner' + '.')
print('Dear ' + names[1].title() + ', you are invited to dinner' + '.')
print('Dear ' + names[2].title() + ', you are invited to dinner' + '.')
print('Dear ' + names[3].title() + ', you are invited to dinner' + '.')
print(lost_guest + " won't come.")
names.insert(0,'Marina')
names.insert(2,"Sasha")
names.append('Roger')
print('New list')
print('Dear ' + names[0].title() + ', you are invited to dinner' + '.')
print('Dear ' + names[1].title() + ', you are invited to dinner' + '.')
print('Dear ' + names[2].title() + ', you are invited to dinner' + '.')
print('Dear ' + names[3].title() + ', you are invited to dinner' + '.')
print('Dear ' + names[4].title() + ', you are invited to dinner' + '.')
print('Dear ' + names[5].title() + ', you are invited to dinner' + '.')
print('Dear ' + names[6].title() + ', you are invited to dinner' + '.')
one_geust = names.pop()
print(one_geust + ' not invited')
two_geust = names.pop()
print(two_geust + ' not invited')
three_geust = names.pop()
print(three_geust + ' not invited')
four_geust = names.pop()
print(four_geust + ' not invited')
five_geust = names.pop()
print(five_geust + ' not invited')
print('New list')
print('Dear ' + names[0].title() + ', you are invited to dinner' + '.')
print('Dear ' + names[1].title() + ', you are invited to dinner' + '.')
del names [0]
del names [0]
print(names)

